### ISSUE TITLE
Use the official HN API

### ISSUE THREAD

**Issue by jomo** [manmal/hn-android#120]
Y Combinator launched an official API, so they can change their HTML without breaking clients like this one.
- http://blog.ycombinator.com/hacker-news-api
- https://github.com/HackerNews/API
- https://hacker-news.firebaseio.com/

**Comment by michaelbarlow7** [comment]
I was going to investigate implementing this, but the API as it is right now seems pretty inefficient.

https://github.com/HackerNews/API

>The v0 API is essentially a dump of our in-memory data structures. We know, what works great locally in memory isn't so hot over the network. Many of the awkward things are just the way HN works internally. Want to know the total number of comments on an article? Traverse the tree and count. Want to know the children of an item? Load the item and get their IDs, then load them. The newest page? Starts at item maxid and walks backward, keeping only the top level stories. Same for Ask, Show, etc.

So to get the front page, for example, there's a call to get the top stories, but this only returns a list of IDs. To get their details (title, score etc), you have to make a call for each individual story. To get all the comments for a story, you have to make a call for each descendent ID sent down with that story, and I think you need to make further requests to get replies to those comments.

It seems more efficient at this stage to continue scraping the HTML from the website, as it effectively does the job of aggregating these calls for us!

The readme on the API's github was updated 8 days ago, so I'm not sure if updates to the API are planned to be coming soon or not.

**Comment by peshkira** [comment]
@michaelbarlow7 Thanks for the input! That is exactly why we are still waiting with this task.
Also, if we switch to the API now, it seems we will loose the login/upvote functionality, because the API is not offering a way to login.

So you are absolutely right, sticking with HTML scraping is the better solution for now.

**Comment by michaelbarlow7** [comment]
Good to see we're on the same page, guess we'll wait for an update then!
