### ISSUE TITLE
Move the refresh action item to the right

### ISSUE THREAD

**Issue by peshkira** [manmal/hn-android#121]
A user reported that after the action bar is in use, the refresh action item is not the last item.
Investigate if it is possible to change the places of the overflow and the refresh menu items and change them if possible.

Having the refresh at the right corner is much more convenient when holding the device with one hand.

**Comment by manmal** [comment]
This is closely related to #186 , so I’ll close those issue for now. If we reconsider handedness, we’ll think about the location of all UI elements.
