### ISSUE TITLE
Opening Comments Thread with Unusually Large Number of Comments Crashes App

### ISSUE THREAD

**Issue by ode79** [manmal/hn-android#124]
Hi,

Opening one of today's front page stories 'Tim Cook Speaks Up' (https://news.ycombinator.com/item?id=8532261) crashes the app. The number of comments was 660 at the time. I don't think I have ever seen a thread with this many comments before, but I have successfully opened threads with 200-300 comments.

On the first attempt the app indicator spins for a few seconds trying to load the comments but then crashes. On further attempts it just crashes immediately without even trying to load the comments.

Tested on a Moto G and Nexus 7.

**Comment by peshkira** [comment]
I have just uploaded a new version 1.9.11 to the play store, which addresses this issue. Please also take a look to my comment here: #129
