### ISSUE TITLE
Fonts Not Anti-Aliasing on Android 5.0

### ISSUE THREAD

**Issue by oemmerson** [manmal/hn-android#125]
I upgraded my Nexus 7 to Lolipop and now the fonts in all areas of HN are not anti-aliased.

If it helps I have also noticed that the font in the address bar of Firefox is not anti-aliased either, although the text on web pages is.

In HN at the medium font setting it's bad enough I can't stand using the app. If I turn the font size to large it's bearable but very distracting.

**Comment by manmal** [comment]
This seems to have been fixed by later Android versions.
