### ISSUE TITLE
Feature request: Collapse Grandparent comment

### ISSUE THREAD

**Issue by jaybong** [manmal/hn-android#132]
It would be good to be able to be reading a deeply nested comment, hold it down, and have the option to collapse it, it's parent(s), and all the way up to the OP. 

I often find I'm deep in a conversation only to realise it's going nowhere, or I actually don't care about that tangent. Rather then scrolling all the way up to the parent to click/collapse it would be a lot easier to be able to do it from within it's children/grandchildren comments.

I would imagine this action would be labeled "collapse grandparent" or similar. 

Love the app btw, probably use it ~15h each week and have tried them all.

**Comment by peshkira** [comment]
I just uploaded version 1.9.11 to the play store, which fixes this issue. Thanks @danieldisu
