### ISSUE TITLE
WebView vulnearbility on Android versions <= 4.3

### ISSUE THREAD

**Issue by revuwa** [manmal/hn-android#143]
I'm using AOSP 4.2 and have to stay on that version for an indefinite period of time.
Now I've read the following:
https://community.rapid7.com/community/metasploit/blog/2015/01/11/google-no-longer-provides-patches-for-webview-jelly-bean-and-prior

Google said to the app developers: "[...] consider providing your own renderer on Android 4.3 and earlier [...]".
Source: https://plus.google.com/+AdrianLudwig/posts/1md7ruEwBLF

If I select, that I want to view articles within the app, I'm using the vulnerable WebView, right?
Are there any plans to create some kind of workaround or solution, for example the mentioned one by Google above?

**Comment by revuwa** [comment]
Hint; here I got some useful informations: https://github.com/anthonycr/Lightning-Browser/issues/193

**Comment by peshkira** [comment]
Thanks, I'll take a look at this project https://github.com/mogoweb/chromium_webview and will try to swap or at least provide a new option to use this web view instead of the default one.
