### ISSUE TITLE
Comments not loading at all / Getting 1.9.9 on F-Droid

### ISSUE THREAD

**Issue by kasbah** [manmal/hn-android#145]
Comments are not loading at all for me with version 1.9.6 from F-Droid (CyanogenMod 11-20141115). I noticed you have a 1.9.9 version so you might have fixed this issue already but is it possible to get it through F-Droid?

**Comment by peshkira** [comment]
The issues with the comments and the login were fixed within 1.9.8 and 1.9.9.
We always submit new versions only to the play store.

However, it seems someone or the F-Droid maintainers already have put the new version out. Please note that this was no official release from us, so we do not know what actually was released there.
