### ISSUE TITLE
The [More] button doesn't work anymore

### ISSUE THREAD

**Issue by revuwa** [manmal/hn-android#146]
I've seen the issue: https://github.com/manmal/hn-android/issues/64 but I thought I'll open a new one, because in my case the [More] button bug was coming up with v1.9.8 of the app, and still exist in v1.9.9.

If I use the [More] button, it seems to load more entries, (and my traffic monitor indicates, that there are real network requests), but it reaches just one more entry, which mostly has no data on upvotes & comments - and nothing more happens.

Example:
![hn01](https://cloud.githubusercontent.com/assets/7300276/6389193/3ddb3642-bda2-11e4-9c46-d8563ca32cef.png)
after hitting [More]:
![hn02](https://cloud.githubusercontent.com/assets/7300276/6389197/4af2935c-bda2-11e4-8136-2a65ff8259db.png)

It would be great, ff this could be fixed in some future versions.

[I'm using AOSP v4.2.2 on a Samsung Galaxy S2 (I9100) device (with 4.3", 480x800 resolution) if this matters].

**Comment by peshkira** [comment]
FIXED in 1.9.10

**Comment by revuwa** [comment]
Thanks so much for your enthusiasm!
It works great.
