### ISSUE TITLE
Crashlytics breaks the build process on F-Droid

### ISSUE THREAD

**Issue by revuwa** [manmal/hn-android#156]
How should I say.
The integration of the (non-free) crashlytics makes it impossible to provide your absolutely great app on free (open source) app-stores like f-droid: https://f-droid.org/wiki/page/com.manuelmaly.hn

I already had that kind of question on another app (Secrecy) already, and here the developer considered to provide a crashlytics free version of his app for f-droid: http://forum.xda-developers.com/showthread.php?p=55391629#post55391629

So I kindly wanted to ask, if you'll see a chance to make your app (crashlytics)-"free" (and so open source) again?
And of course I'm very thankful for any other hint to see your wonderful app back on f-droid.

**Comment by manmal** [comment]
Closing this since HN is listed on f-droid now.
