### ISSUE TITLE
[Feature] Pull down to refresh

### ISSUE THREAD

**Issue by tbroadley** [manmal/hn-android#163]
I think it would be nice to be able to pull down on the main page of the app to refresh the posts list, or to pull down on a comments page to refresh that.

If you think it would be a good addition to the app, I am interested in implementing it.

**Comment by peshkira** [comment]
Sure, why not! :) 

When we started with the app, this was not really the android way. Meanwhile it is actually used by many Google apps as well. Will you implement it with SwipeRefreshLayout or do you have something else in mind?

**Comment by tbroadley** [comment]
Yes, I was thinking of SwipeRefreshLayout. I don't have any experience with it, but I'd like to learn!

I'll make a pull request when I have something to show.

**Comment by drewnoakes** [comment]
+1 for this feature!
