### ISSUE TITLE
Unable to vote any post

### ISSUE THREAD

**Issue by aviaryan** [manmal/hn-android#171]
Since a last few days, I have been noticing that all posts are by default marked as "upvoted by you". So I am unable to vote any post.

**Comment by peshkira** [comment]
I just tried it and it seems to work.
Could you please log out and log back in again. If the problem persists, could you please let me know, what android version and what kind of device do you have.

Thanks!

**Comment by aviaryan** [comment]
Logging out and then logging back in fixed the problem.

**Comment by peshkira** [comment]
great! Probably HN changed something internally.
Thanks for closing it.
