### ISSUE TITLE
Material design

### ISSUE THREAD

**Issue by sedrubal** [manmal/hn-android#176]
This app uses a very custom design. I think it would be better to use the modern, clean and simple material design ;)

**Comment by ocdtrekkie** [comment]
Pretty sure there are materitrash designed apps available already if you want one.

https://play.google.com/store/search?q=hacker%20news%20material

I'm not this app's dev, and my opinion doesn't matter, but I specifically was interested in this app because it wasn't material.

**Comment by sedrubal** [comment]
But it's the only one in f-droid ;)

**Comment by peshkira** [comment]
Hi! Thanks for this report. Unfortunately, currently there are no plans to migrate to a more materially designed version of the app. We wanted to refresh the design a bit (not really materially), but currently we do not have enough time to undertake larger changes in this project, so we just maintain the repository and do critical fixes (like the one last week).

Also we are quite happy with the current design. Even though it is outdated, it seems that most of the users still like it.

There are plenty of other HN apps and some of them are adopting the material guidelines well. Maybe you can ask the authors to open source them and/or publish them on f-droid.

I hope this does not come as a big disappointment  to you :)

**Comment by sedrubal** [comment]
It's OK ;)
