### ISSUE TITLE
Comments are not displayes

### ISSUE THREAD

**Issue by oceanofsolaris** [manmal/hn-android#177]
While the button to show comments now shows again, a new issue has turned up. Now I don't get any of the comments displayed. The comment page loads for a while but remains empty (same as when looking at comments for an article with zero comments). This broke around yesterday without the App receiving am update, so I assume the problem is due to a change in the data returned by news.ycombinator.com.

P.S: Sorry for the typos and bad formatting, I am currently on mobile.

**Comment by JulianD** [comment]
I am experiencing the same problem. I thought it was because I updated to nougat.

**Comment by qazmonk** [comment]
I am also experiencing this issue

**Comment by Chris911** [comment]
Same here. Started happening a couple days ago.

**Comment by rmalleman** [comment]
I am also experiencing this

**Comment by mxm** [comment]
Same here. Comment parsing seems to be broken.

**Comment by peshkira** [comment]
The PR of @vafada fixes the issue. Thank you.

I will shortly look at the other PRs and will be releasing a new version within the hour. Thanks for all the reports

**Comment by mxm** [comment]
Thank you for the fast reply!
