### ISSUE TITLE
Request: Support Hacker News Digest links

### ISSUE THREAD

**Issue by strayer** [manmal/hn-android#187]
I exclusively consume Hacker News through the daily [Hacker News Digest](https://www.hndigest.com/). Sadly, they seem to track URLs and don't link directly to ycombinator. Instead they have two types of links:

Story link: https://www.hndigest.com/m/yJX0Km9c2DwVgOvh_3gfWQ==/s/91682
Comments link: https://www.hndigest.com/m/yJX0Km9c2DwVgOvh_3gfWQ==/c/91682

It would be terrific if hn-android would also handle the comments links of hndigest, so I don't have to first open Firefox for Android, wait for the redirect, and then be able to press the "open in app" button for hn-android.

Example response for the comments link above:

```
< HTTP/1.1 302 Found
< Server: Cowboy
< Date: Thu, 13 Dec 2018 19:39:22 GMT
< Connection: keep-alive
< X-Frame-Options: SAMEORIGIN
< X-Xss-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Location: https://news.ycombinator.com/item?id=18663860
< Content-Type: text/html; charset=utf-8
< Cache-Control: no-cache
< X-Runtime: 0.060106
< Strict-Transport-Security: max-age=15552000; includeSubDomains
< Transfer-Encoding: chunked
< Via: 1.1 vegur
```

**Comment by manmal** [comment]
@strayer If you even still use our app: I understand that opening the link in Firefox first is a hassle to go through. On the other hand, we don't want to support platforms that track their users. If this really bothers you, one solution I can think of is that you create a fork of this repo and create your own flavor of the app - if anything is unclear to you during that customization process, you can create a new issue here.
