### ISSUE TITLE
Broken after recent updates

### ISSUE THREAD

**Issue by quantum-x** [manmal/hn-android#189]
Hello - 
Thanks for such a great app. It seems that recent changes on the HN side have broken the app.
Just a head's up in case you're still maintaining the app.

**Comment by cwilson** [comment]
I agree--was very sad to see this app stop working. I took a shot at fixing it: https://github.com/manmal/hn-android/pull/190. I don't have Android yet experience so it'd be great if someone can take a look.

**Comment by mator** [comment]
@manmal any chance to review or update the app? there's like half internetz wish it could still work

**Comment by manmal** [comment]
Thanks for the feedback! We'll look into it - maybe a fix can be found that allows us to upload a new build of the app as it is now.

**Comment by manmal** [comment]
This has been fixed by #190. The new build is [available on the Play Store](https://play.google.com/store/apps/details?id=com.manuelmaly.hn). 

Thanks everybody for reporting this, much appreciated!

**Comment by quantum-x** [comment]
Thanks very much !
