### ISSUE TITLE
Upvoting bug

### ISSUE THREAD

**Issue by maltzj** [manmal/hn-android#46]
I ran into a bug earlier today which doesn't seem to want to reproduce itself.  The steps for it are:

Go to a post, upvote a comment in it
Back out of the post
Go back to the post, try to upvote the same comment
See "upvote" instead of "already upvoted by you"

I've looked a little bit into the code to find this and it looks like it might be an issue with how the comments are cached.  The app might not be caching whether the user has already voted on a comment or not.  I'll investigate further when I get a chance.

**Comment by lnalex** [comment]
I try to reproduce the bug but works fine on my part, still the same on yours ?

**Comment by peshkira** [comment]
I haven't been able to reproduce it as well. However, it could really be the case. We wanted to rewrite a lot of the app, but our priorities have shifted a bit and we do not have much time for HN. Currently we fix only major bugs and appreciate any input and/or PR
